// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.activity.shared.ActivityMapper;
import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceController;
import com.google.inject.Inject;
import com.puglieseweb.test.trms.client.managed.request.ApplicationEntityTypesProcessor;
import com.puglieseweb.test.trms.client.managed.request.ApplicationRequestFactory;
import com.puglieseweb.test.trms.client.managed.request.TaxiProxy;
import com.puglieseweb.test.trms.client.managed.ui.TaxiListView;
import com.puglieseweb.test.trms.client.managed.ui.TaxiMobileListView;
import com.puglieseweb.test.trms.client.scaffold.ScaffoldApp;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationMasterActivities_Roo_Gwt implements ActivityMapper {

    protected ApplicationRequestFactory requests;

    protected PlaceController placeController;

    public Activity getActivity(Place place) {
        if (!(place instanceof ProxyListPlace)) {
            return null;
        }
        ProxyListPlace listPlace = (ProxyListPlace) place;
        return new ApplicationEntityTypesProcessor<Activity>() {

            @Override
            public void handleTaxi(TaxiProxy isNull) {
                setResult(new TaxiListActivity(requests, ScaffoldApp.isMobile() ? TaxiMobileListView.instance() : TaxiListView.instance(), placeController));
            }
        }.process(listPlace.getProxyClass());
    }
}
