// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.activity;

import com.google.gwt.activity.shared.Activity;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.place.shared.Place;
import com.google.gwt.requestfactory.shared.EntityProxyId;
import com.google.gwt.requestfactory.shared.Receiver;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.puglieseweb.test.trms.client.managed.activity.TaxiEditActivityWrapper.View;
import com.puglieseweb.test.trms.client.managed.request.ApplicationRequestFactory;
import com.puglieseweb.test.trms.client.managed.request.TaxiProxy;
import com.puglieseweb.test.trms.client.scaffold.activity.IsScaffoldMobileActivity;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyEditView;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyListPlace;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyPlace;
import com.puglieseweb.test.trms.shared.domain.TaxiOptions;
import com.puglieseweb.test.trms.shared.domain.TaxiRankLocations;
import com.puglieseweb.test.trms.shared.domain.TaxiStatus;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

public abstract class TaxiEditActivityWrapper_Roo_Gwt implements Activity, IsScaffoldMobileActivity {

    protected Activity wrapped;

    protected View<?> view;

    protected ApplicationRequestFactory requests;

    @Override
    public void start(AcceptsOneWidget display, EventBus eventBus) {
        view.setLocationPickerValues(Arrays.asList(TaxiRankLocations.values()));
        view.setStatusPickerValues(Arrays.asList(TaxiStatus.values()));
        view.setAddOptionPickerValues(Arrays.asList(TaxiOptions.values()));
        wrapped.start(display, eventBus);
    }

    public interface View_Roo_Gwt<V extends com.puglieseweb.test.trms.client.scaffold.place.ProxyEditView<com.puglieseweb.test.trms.client.managed.request.TaxiProxy, V>> extends ProxyEditView<TaxiProxy, V> {

        void setLocationPickerValues(Collection<TaxiRankLocations> values);

        void setStatusPickerValues(Collection<TaxiStatus> values);

        void setAddOptionPickerValues(Collection<TaxiOptions> values);
    }
}
