// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.cellview.client.CellTable;
import com.google.gwt.user.cellview.client.HasKeyboardSelectionPolicy.KeyboardSelectionPolicy;
import com.google.gwt.user.cellview.client.TextColumn;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.puglieseweb.test.trms.client.managed.request.TaxiProxy;
import com.puglieseweb.test.trms.client.scaffold.place.AbstractProxyListView;
import com.puglieseweb.test.trms.shared.domain.TaxiOptions;
import com.puglieseweb.test.trms.shared.domain.TaxiRankLocations;
import com.puglieseweb.test.trms.shared.domain.TaxiStatus;
import java.util.HashSet;
import java.util.Set;

public abstract class TaxiListView_Roo_Gwt extends AbstractProxyListView<TaxiProxy> {

    @UiField
    CellTable<TaxiProxy> table;

    protected Set<String> paths = new HashSet<String>();

    public void init() {
        paths.add("id");
        table.addColumn(new TextColumn<TaxiProxy>() {

            Renderer<java.lang.Long> renderer = new AbstractRenderer<java.lang.Long>() {

                public String render(java.lang.Long obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(TaxiProxy object) {
                return renderer.render(object.getId());
            }
        }, "Id");
        paths.add("version");
        table.addColumn(new TextColumn<TaxiProxy>() {

            Renderer<java.lang.Integer> renderer = new AbstractRenderer<java.lang.Integer>() {

                public String render(java.lang.Integer obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(TaxiProxy object) {
                return renderer.render(object.getVersion());
            }
        }, "Version");
        paths.add("location");
        table.addColumn(new TextColumn<TaxiProxy>() {

            Renderer<com.puglieseweb.test.trms.shared.domain.TaxiRankLocations> renderer = new AbstractRenderer<com.puglieseweb.test.trms.shared.domain.TaxiRankLocations>() {

                public String render(com.puglieseweb.test.trms.shared.domain.TaxiRankLocations obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(TaxiProxy object) {
                return renderer.render(object.getLocation());
            }
        }, "Location");
        paths.add("status");
        table.addColumn(new TextColumn<TaxiProxy>() {

            Renderer<com.puglieseweb.test.trms.shared.domain.TaxiStatus> renderer = new AbstractRenderer<com.puglieseweb.test.trms.shared.domain.TaxiStatus>() {

                public String render(com.puglieseweb.test.trms.shared.domain.TaxiStatus obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(TaxiProxy object) {
                return renderer.render(object.getStatus());
            }
        }, "Status");
        paths.add("addOption");
        table.addColumn(new TextColumn<TaxiProxy>() {

            Renderer<com.puglieseweb.test.trms.shared.domain.TaxiOptions> renderer = new AbstractRenderer<com.puglieseweb.test.trms.shared.domain.TaxiOptions>() {

                public String render(com.puglieseweb.test.trms.shared.domain.TaxiOptions obj) {
                    return obj == null ? "" : String.valueOf(obj);
                }
            };

            @Override
            public String getValue(TaxiProxy object) {
                return renderer.render(object.getAddOption());
            }
        }, "Add Option");
    }
}
