// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.DivElement;
import com.google.gwt.dom.client.Element;
import com.google.gwt.dom.client.Style.Display;
import com.google.gwt.editor.client.EditorError;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.shared.EventBus;
import com.google.gwt.requestfactory.client.RequestFactoryEditorDriver;
import com.google.gwt.requestfactory.shared.RequestFactory;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.DoubleBox;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.IntegerBox;
import com.google.gwt.user.client.ui.LongBox;
import com.google.gwt.user.client.ui.TextBox;
import com.google.gwt.user.client.ui.ValueListBox;
import com.google.gwt.user.datepicker.client.DateBox;
import com.puglieseweb.test.trms.client.managed.activity.TaxiEditActivityWrapper;
import com.puglieseweb.test.trms.client.managed.activity.TaxiEditActivityWrapper.View;
import com.puglieseweb.test.trms.client.managed.request.TaxiProxy;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyEditView;
import com.puglieseweb.test.trms.client.scaffold.ui.*;
import com.puglieseweb.test.trms.shared.domain.TaxiOptions;
import com.puglieseweb.test.trms.shared.domain.TaxiRankLocations;
import com.puglieseweb.test.trms.shared.domain.TaxiStatus;
import java.util.Collection;
import java.util.List;

public abstract class TaxiMobileEditView_Roo_Gwt extends Composite implements View<TaxiMobileEditView> {

    @UiField(provided = true)
    ValueListBox<TaxiRankLocations> location = new ValueListBox<TaxiRankLocations>(new AbstractRenderer<com.puglieseweb.test.trms.shared.domain.TaxiRankLocations>() {

        public String render(com.puglieseweb.test.trms.shared.domain.TaxiRankLocations obj) {
            return obj == null ? "" : String.valueOf(obj);
        }
    });

    @UiField(provided = true)
    ValueListBox<TaxiStatus> status = new ValueListBox<TaxiStatus>(new AbstractRenderer<com.puglieseweb.test.trms.shared.domain.TaxiStatus>() {

        public String render(com.puglieseweb.test.trms.shared.domain.TaxiStatus obj) {
            return obj == null ? "" : String.valueOf(obj);
        }
    });

    @UiField(provided = true)
    ValueListBox<TaxiOptions> addOption = new ValueListBox<TaxiOptions>(new AbstractRenderer<com.puglieseweb.test.trms.shared.domain.TaxiOptions>() {

        public String render(com.puglieseweb.test.trms.shared.domain.TaxiOptions obj) {
            return obj == null ? "" : String.valueOf(obj);
        }
    });

    public void setAddOptionPickerValues(Collection<TaxiOptions> values) {
        addOption.setAcceptableValues(values);
    }

    public void setStatusPickerValues(Collection<TaxiStatus> values) {
        status.setAcceptableValues(values);
    }

    public void setLocationPickerValues(Collection<TaxiRankLocations> values) {
        location.setAcceptableValues(values);
    }
}
