// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import com.puglieseweb.test.trms.client.managed.request.TaxiProxy;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyDetailsView;
import com.puglieseweb.test.trms.client.scaffold.place.ProxyListView;
import com.puglieseweb.test.trms.shared.domain.TaxiOptions;
import com.puglieseweb.test.trms.shared.domain.TaxiRankLocations;
import com.puglieseweb.test.trms.shared.domain.TaxiStatus;

public abstract class TaxiDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<TaxiProxy> {

    @UiField
    SpanElement id;

    @UiField
    SpanElement version;

    @UiField
    SpanElement location;

    @UiField
    SpanElement status;

    @UiField
    SpanElement addOption;

    TaxiProxy proxy;

    @UiField
    SpanElement displayRenderer;

    public void setValue(TaxiProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        location.setInnerText(proxy.getLocation() == null ? "" : String.valueOf(proxy.getLocation()));
        status.setInnerText(proxy.getStatus() == null ? "" : String.valueOf(proxy.getStatus()));
        addOption.setInnerText(proxy.getAddOption() == null ? "" : String.valueOf(proxy.getAddOption()));
        displayRenderer.setInnerText(com.puglieseweb.test.trms.client.managed.ui.TaxiProxyRenderer.instance().render(proxy));
    }
}
