// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.request;

import com.puglieseweb.test.trms.shared.gae.MakesGaeRequests;
import com.puglieseweb.test.trms.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory, MakesGaeRequests {

    TaxiRequest taxiRequest();
}
