// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.puglieseweb.test.trms.server.domain.Taxi")
@ServiceName("com.puglieseweb.test.trms.server.domain.Taxi")
public interface TaxiRequest extends RequestContext {

    abstract Request<java.lang.Long> countTaxis();

    abstract Request<java.util.List<com.puglieseweb.test.trms.client.managed.request.TaxiProxy>> findAllTaxis();

    abstract Request<java.util.List<com.puglieseweb.test.trms.client.managed.request.TaxiProxy>> findTaxiEntries(int firstResult, int maxResults);

    abstract Request<com.puglieseweb.test.trms.client.managed.request.TaxiProxy> findTaxi(Long id);

    abstract InstanceRequest<com.puglieseweb.test.trms.client.managed.request.TaxiProxy, java.lang.Void> remove();

    abstract InstanceRequest<com.puglieseweb.test.trms.client.managed.request.TaxiProxy, java.lang.Void> persist();
}
