// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.puglieseweb.test.trms.client.managed.request;

import com.google.gwt.requestfactory.shared.EntityProxy;
import com.google.gwt.requestfactory.shared.ProxyForName;
import com.puglieseweb.test.trms.shared.domain.TaxiOptions;
import com.puglieseweb.test.trms.shared.domain.TaxiRankLocations;
import com.puglieseweb.test.trms.shared.domain.TaxiStatus;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.puglieseweb.test.trms.server.domain.Taxi")
@ProxyForName("com.puglieseweb.test.trms.server.domain.Taxi")
public interface TaxiProxy extends EntityProxy {

    abstract Long getId();

    abstract Integer getVersion();

    abstract TaxiRankLocations getLocation();

    abstract TaxiStatus getStatus();

    abstract TaxiOptions getAddOption();

    abstract void setId(Long id);

    abstract void setVersion(Integer version);

    abstract void setLocation(TaxiRankLocations location);

    abstract void setStatus(TaxiStatus status);

    abstract void setAddOption(TaxiOptions addOption);
}
