// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.puglieseweb.test.trms.server.domain;

import com.puglieseweb.test.trms.server.domain.Taxi;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect TaxiDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TaxiDataOnDemand: @Component;
    
    private Random TaxiDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Taxi> TaxiDataOnDemand.data;
    
    public Taxi TaxiDataOnDemand.getNewTransientTaxi(int index) {
        com.puglieseweb.test.trms.server.domain.Taxi obj = new com.puglieseweb.test.trms.server.domain.Taxi();
        obj.setLocation(com.puglieseweb.test.trms.shared.domain.TaxiRankLocations.class.getEnumConstants()[0]);
        obj.setStatus(com.puglieseweb.test.trms.shared.domain.TaxiStatus.class.getEnumConstants()[0]);
        obj.setAddOption(com.puglieseweb.test.trms.shared.domain.TaxiOptions.class.getEnumConstants()[0]);
        return obj;
    }
    
    public Taxi TaxiDataOnDemand.getSpecificTaxi(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Taxi obj = data.get(index);
        return Taxi.findTaxi(obj.getId());
    }
    
    public Taxi TaxiDataOnDemand.getRandomTaxi() {
        init();
        Taxi obj = data.get(rnd.nextInt(data.size()));
        return Taxi.findTaxi(obj.getId());
    }
    
    public boolean TaxiDataOnDemand.modifyTaxi(Taxi obj) {
        return false;
    }
    
    public void TaxiDataOnDemand.init() {
        data = com.puglieseweb.test.trms.server.domain.Taxi.findTaxiEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Taxi' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.puglieseweb.test.trms.server.domain.Taxi>();
        for (int i = 0; i < 10; i++) {
            com.puglieseweb.test.trms.server.domain.Taxi obj = getNewTransientTaxi(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
