// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.puglieseweb.test.trms.server.domain;

import com.puglieseweb.test.trms.server.domain.TaxiRank;
import java.lang.Integer;
import java.lang.Long;
import java.lang.SuppressWarnings;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TaxiRank_Roo_Entity {
    
    declare @type: TaxiRank: @Entity;
    
    @PersistenceContext
    transient EntityManager TaxiRank.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long TaxiRank.id;
    
    @Version
    @Column(name = "version")
    private Integer TaxiRank.version;
    
    public Long TaxiRank.getId() {
        return this.id;
    }
    
    public void TaxiRank.setId(Long id) {
        this.id = id;
    }
    
    public Integer TaxiRank.getVersion() {
        return this.version;
    }
    
    public void TaxiRank.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void TaxiRank.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TaxiRank.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TaxiRank attached = TaxiRank.findTaxiRank(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TaxiRank.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TaxiRank.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TaxiRank TaxiRank.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TaxiRank merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager TaxiRank.entityManager() {
        EntityManager em = new TaxiRank().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    @Transactional
    public static long TaxiRank.countTaxiRanks() {
        return ((Number) entityManager().createQuery("select count(o) from TaxiRank o").getSingleResult()).longValue();
    }
    
    @SuppressWarnings("unchecked")
    @Transactional
    public static List<TaxiRank> TaxiRank.findAllTaxiRanks() {
        return entityManager().createQuery("select o from TaxiRank o").getResultList();
    }
    
    @Transactional
    public static TaxiRank TaxiRank.findTaxiRank(Long id) {
        if (id == null) return null;
        Query query = entityManager().createQuery("select o from TaxiRank o where o.id = :id").setParameter("id",id);
        TaxiRank result = null;
        List results = query.getResultList();
        if (results.size() > 0) {
            result = (TaxiRank) results.get(0);
        }
        return result;
    }
    
    @SuppressWarnings("unchecked")
    @Transactional
    public static List<TaxiRank> TaxiRank.findTaxiRankEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("select o from TaxiRank o").setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
